FROM python:3.7.3
LABEL maintainer = gina
ENV PYTHONUNBUFFERED 1
RUN mkdir /docker_api
WORKDIR /docker_api
COPY . /docker_api
EXPOSE 80

RUN pip install requests
RUN pip install beautifulsoup4

VOLUME ["D:/Docker Toolbox/PTT"]